Create a framework WorkUnit Class
dirac-institute/kbmod pull request #368
Opened 2023-10-04 17:11 UTC by jeremykubica

This PR is an example of how we could structure the input reading and writing of a KBMOD `WorkUnit`. It builds off PR #366.

2023-10-05 22:36 UTC, DinoBektesevic requested changes
Using named header units would help a lot so I'd most recommend them.
I would restructure how SearchConfiguration (de)serializes itself, as in naming not in scope, so that we can create on-the-fly strings. 

I am very tepid about pickling anything, I've usually nothing but slight annoyance with it. I would remove support for that here, short of if there's anything we strictly need - in which case I would make it an internal job to write that to string in a way that it roundtrips. 

You expressed some concern about being on the right track here, but yes, this is basically exactly what we talked about regarding building serializable processable units.

2023-10-05 22:36 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +            config_table = Table(hdul[2].data)
I was kind of wondering earlier why you wouldn't just write the config as a header, is there a variable we have that breaks the length limit or something?

2023-10-05 22:36 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +        return result
`return WorkUnit(im_stack=im_stack, config=config)`?

2023-10-05 22:36 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +                ext_num = 3 + 4 * i
This convinces me we should just use named HDUs.

2023-10-05 22:36 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +                    p = PSF(1e-8)
We are the sole creator of these files. I think we should just throw an error if we don't have everything we need before writing it to begin with. Or make these defaults the matter of RawImage/PSF constructors or something and write whatever they make to disk.

2023-10-05 22:36 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +    np_pixels = np.array(img.get_all_pixels()).astype("float32", casting="same_kind")
img is `RawImage` no, a list of `float32` already. Why not just instantiate `np.array(img.get_all_pixels(), dtype=np.single)` and avoid a cast to double's and then to floats altogether.

2023-10-05 22:36 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +    if hdu.header["NAXIS"] == 2:
I think it's better to be checking `if isinstance(hdu, (ImageHDU, CompImageHDU)` because those are the two image HDU types.

2023-10-06 11:34 UTC, jeremykubica commented on src/kbmod/configuration.py
> +            # If Table does not understand the type, pickle it.
That's fair. The only thing this is supporting is dictionaries and None. I originally had the code write these out as strings, but thought using pickle might reduce the code complexity. I'm happy to change it back.

2023-10-06 11:35 UTC, jeremykubica commented on src/kbmod/configuration.py
> +        layer : `int`
Nice. I wasn't aware that FITS supported named headers.

2023-10-06 11:36 UTC, jeremykubica commented on src/kbmod/configuration.py
> +    def set_from_table(self, t, strict=True):
Sounds good.

2023-10-11 18:56 UTC, jeremykubica commented
I think I got all of your requested changes. For not FITS is the only output format, but we can add `to_` and `from_` functions for other formats.

2023-10-11 22:16 UTC, DinoBektesevic approved these changes
Looks great!

2023-10-11 22:16 UTC, DinoBektesevic commented on src/kbmod/work_unit.py
> +            3+ - Image extensions for the science layer ("SCI_i"),
Remember that the docstrings are markdown rendered into documentation by Sphinx. To render a proper list that discriminates between references and literals try:

```
The FITS file will have at least the following extensions:

0. ``PRIMARY`` extension
1. ``METADATA`` extension containing provenance 
2. ``KBMOD_CONFIG`` extension containing search parameters
3. (+) any additional image extensions are named ``SCI_i``, ``VAR_i``, ``MSK_i`` 
and ``PSF_i`` for the science, variance, mask and PSF of each image respectively, 
where ``i`` runs from 0 to number of images in the `WorkUnit`.
```

2023-10-12 12:01 UTC, merged